language: haskell

befor_install:
 - cabal update
 - cabal install hspec doctest cabal-meta cabal-src
 - cabal-meta install --force-reinstalls
 - cabal install hpc-coveralls

script:
 - mega-sdist --test
 - cabal configure --enable-tests --enable-library-coverage
 - cabal build
 - /home/travis/.cabal/run-cabal-test --show-details=always

after_script:
 - hpc-coveralls test