language: haskell

befor_install:
 - cabal update
 - cabal install hspec doctest cabal-src
 - cabal install hpc-coveralls
 - cabal install --only-dependencies --enable-tests

script:
 - cabal configure --enable-tests --enable-library-coverage
 - cabal build
 - /home/travis/.cabal/run-cabal-test --show-details=always

after_script:
 - hpc-coveralls test